# 注册到 Eureka 服务中心
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      # 注册到集群，就把多个 Eureka server 地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      # defaultZone: http://eureka.oddity.cn:8091/eureka,http://eureka.oddity.cn:8092/eureka,http://eureka.oddity.cn:8093/eureka
      defaultZone: http://eureka.oddity.cn:8090/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称 :${spring.application.name}:@project.version@
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # lease-renewal-interval-in-seconds: 1 # 客户端向注册中心发送心跳的时间间隔，（默认30秒）
    # lease-expiration-duration-in-seconds: 2 # Eureka 注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
    # 自定义Eureka元数据
    metadata-map:
      cluster: 123
      region: 321
